In [4]:
# %load jupyter
# standard imports

# print everything
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import sys
print('python:', sys.version_info[:3])

import numpy as np
print('numpy:', np.__version__)

import pandas as pd
print('pandas:', pd.__version__)

import sklearn as sk
print('sklearn:', sk.__version__)

import tensorflow as tf
print('tensorflow:', tf.__version__)

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
print('seaborn:', sns.__version__)
plt.style.use('ggplot')

python: (3, 7, 3)
numpy: 1.16.4
pandas: 0.24.2
sklearn: 0.21.2
tensorflow: 1.14.0
seaborn: 0.9.0

In [63]:
bom_movie_gross_df = pd.read_csv('data/bom.movie_gross.csv.gz')
bom_movie_gross_df.head(100)
bom_movie_gross_df.info()

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
5,The Twilight Saga: Eclipse,Sum.,300500000.0,398000000,2010
6,Iron Man 2,Par.,312400000.0,311500000,2010
7,Tangled,BV,200800000.0,391000000,2010
8,Despicable Me,Uni.,251500000.0,291600000,2010
9,How to Train Your Dragon,P/DW,217600000.0,277300000,2010
10,Clash of the Titans (2010),WB,163200000.0,330000000,2010
11,The Chronicles of Narnia: The Voyage of the Da...,Fox,104400000.0,311300000,2010
12,The King's Speech,Wein.,135500000.0,275400000,2010
13,Tron Legacy,BV,172100000.0,228000000,2010
14,The Karate Kid,Sony,176600000.0,182500000,2010
15,Prince of Persia: The Sands of Time,BV,90800000.0,245600000,2010
16,Black Swan,FoxS,107000000.0,222400000,2010
17,Megamind,P/DW,148400000.0,173500000,2010
18,Robin Hood,Uni.,105300000.0,216400000,2010
19,The Last Airbender,Par.,131800000.0,187900000,2010
20,Little Fockers,Uni.,148400000.0,162200000,2010
21,Resident Evil: Afterlife,SGem,60100000.0,240100000,2010
22,Shutter Island,Par.,128000000.0,166800000,2010
23,Salt,Sony,118300000.0,175200000,2010
24,Sex and the City 2,WB (NL),95300000.0,193000000,2010
25,The Tourist,Sony,67600000.0,210700000,2010
26,The Expendables,LGF,103100000.0,171400000,2010
27,Grown Ups,Sony,162000000.0,109400000,2010
28,Knight & Day,Fox,76400000.0,185500000,2010
29,True Grit,Par.,171200000.0,81000000,2010
...,...,...,...,...,...
70,The Last Song,BV,63000000.0,26100000,2010
71,Dinner for Schmucks,P/DW,73000000.0,13800000,2010
72,Marmaduke,Fox,33600000.0,50100000,2010
73,Piranha 3D,W/Dim.,25000000.0,58200000,2010
74,Oceans,BV,19400000.0,63200000,2010
75,Edge of Darkness,WB,43300000.0,37800000,2010
76,Vampires Suck,Fox,36700000.0,43900000,2010
77,Letters to Juliet,Sum.,53000000.0,26100000,2010
78,The Back-Up Plan,CBS,37500000.0,40000000,2010
79,If You Are the One 2 (Fei Cheng Wu Rao II),CL,427000.0,75600000,2010
80,Diary of a Wimpy Kid,Fox,64000000.0,11700000,2010
81,Easy A,SGem,58400000.0,16600000,2010
82,Hubble 3D,WB,52400000.0,21500000,2010
83,Takers,SGem,57700000.0,11300000,2010
84,Tales from Earthsea,BV,48500.0,68600000,2010
85,Legion (2010),SGem,40200000.0,27800000,2010
86,The American,Focus,35600000.0,32299999,2010
87,The Last Exorcism,LGF,41000000.0,26700000,2010
88,The Next Three Days,LGF,21100000.0,46300000,2010
89,The Girl Who Played with Fire,MBox,7600000.0,59500000,2010
90,Skyline,Uni.,21400000.0,45400000,2010
91,Hot Tub Time Machine,MGM,50300000.0,14300000,2010
92,Devil,Uni.,33600000.0,29100000,2010
93,127 Hours,FoxS,18300000.0,42400000,2010
94,Tyler Perry's Why Did I Get Married Too?,LGF,60100000.0,578000,2010
95,Secretariat,BV,59700000.0,537000,2010
96,The Ghost Writer,Sum.,15500000.0,44700000,2010
97,Morning Glory,Par.,31000000.0,29000000,2010
98,Remember Me,Sum.,19100000.0,37000000,2010
99,Cop Out,WB,44900000.0,10700000,2010

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
title             3387 non-null object
studio            3382 non-null object
domestic_gross    3359 non-null float64
foreign_gross     2037 non-null object
year              3387 non-null int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB

In [110]:
bom_movie_gross_df['foreign_gross'] = pd.to_numeric(bom_movie_gross_df['foreign_gross'], errors = 'coerce')
bom_movie_gross_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 6 columns):
title             3387 non-null object
studio            3382 non-null object
domestic_gross    3359 non-null float64
foreign_gross     2032 non-null float64
year              3387 non-null int64
total_gross       2004 non-null float64
dtypes: float64(3), int64(1), object(2)
memory usage: 158.8+ KB

In [111]:
#creating a new column with the total_gross (domestic+foreign)
bom_movie_gross_df['total_gross'] = bom_movie_gross_df['foreign_gross'] + bom_movie_gross_df['domestic_gross']
bom_movie_gross_df.head()

,title,studio,domestic_gross,foreign_gross,year,total_gross
0,Toy Story 3,BV,415000000.0,652000000.0,2010,1.067000e+09
1,Alice in Wonderland (2010),BV,334200000.0,691300000.0,2010,1.025500e+09
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000.0,2010,9.603000e+08
3,Inception,WB,292600000.0,535700000.0,2010,8.283000e+08
4,Shrek Forever After,P/DW,238700000.0,513900000.0,2010,7.526000e+08

In [114]:
bom_movie_gross_df.describe()

       domestic_gross  foreign_gross         year   total_gross
count    3.359000e+03   2.032000e+03  3387.000000  2.004000e+03
mean     2.874585e+07   7.505704e+07  2013.958075  1.215769e+08
std      6.698250e+07   1.375294e+08     2.478141  2.061554e+08
min      1.000000e+02   6.000000e+02  2010.000000  4.900000e+03
25%      1.200000e+05   3.775000e+06  2012.000000  8.117750e+06
50%      1.400000e+06   1.890000e+07  2014.000000  4.210000e+07
75%      2.790000e+07   7.505000e+07  2016.000000  1.327250e+08
max      9.367000e+08   9.605000e+08  2018.000000  1.518900e+09

# 1. Exploratory Data Analysis on BOM data

Data collected from Box Office Mojo: 

https://www.boxofficemojo.com/yearly/chart/?view2=worldwide&yr=2010&p=.htm

shows **3387** movie *titles* from *2010* to *2018*
with **3359** doemstic gross values and **2032** foreign gross values.

In [115]:
#creating graphs from title and total gross on 2014-2018